name: flutter_swipecards
description: Tinder(TanTan) Card Widget, fast way to have a high quality swap
  card widget in your flutter app.
version: 0.2.1
homepage: https://github.com/Yash-Garg/flutter_swipecards

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
